#!/bin/bash

set -e
set -x

case "$SUITE" in
  experimental)
    dd-schroot-cmd -c "$SESSION_ID" -y -- apt-get install clang/experimental
    ;;
  *)
    dd-schroot-cmd -c "$SESSION_ID" -y -- apt-get install clang
    ;;
esac
