#!/bin/bash
set -x
set -e

configure_args=""
configure_args="$configure_args --enable-verbose-debug=${CONFIGURE_VERBOSE_DEBUG%-*}"
configure_args="$configure_args --enable-thread-support=${CONFIGURE_THREAD_SUPPORT%-*}"
configure_args="$configure_args --enable-malloc-replacement=${CONFIGURE_MALLOC_REPLACEMENT%-*}"
configure_args="$configure_args --enable-openssl=${CONFIGURE_OPENSSL%-*}"
configure_args="$configure_args --enable-debug-mode=${CONFIGURE_DEBUG_MODE%-*}"

./autogen.sh
./configure --enable-gcc-warnings --disable-silent-rules $configure_args
make -k
make -k check
if [ "${CONFIGURE_VERBOSE_DEBUG%-*}" = yes ] &&
   [ "${CONFIGURE_THREAD_SUPPORT%-*}" = yes ] &&
   [ "${CONFIGURE_MALLOC_REPLACEMENT%-*}" = yes ] &&
   [ "${CONFIGURE_OPENSSL%-*}" = yes ] &&
   [ "${CONFIGURE_DEBUG_MODE%-*}" = yes ]; then
    make -k distcheck
fi
