#!/bin/bash

set -e
set -x
set -u

merge_release_maint() {
  local pkggitdir="$1"; shift
  local relbranch="$1"; shift
  local mntbranch="$1"; shift

  pushd .
  cd "$pkggitdir"

  git branch -t $relbranch origin/$relbranch || true
  git branch -t $mntbranch origin/$mntbranch || true

  local relrev=$(git rev-parse --short "$relbranch")
  if [ -z "$relrev" ]; then echo >&2 "Could not get revision of release branch $relbranch."; exit 1; fi
  local mntrev=$(git rev-parse --short "$mntbranch")
  if [ -z "$mntrev" ]; then echo >&2 "Could not get revision of maintenance branch $mntbranch."; exit 1; fi
  git checkout "$relbranch"
  git merge --no-commit "$mntbranch"

  pkgrev="$relrev+$mntrev"
  popd
}

fudge_upstream_version() {
  local pkggitdir="$1"; shift

  pushd .
  cd "$pkggitdir"

  if [ "$(grep -c AC_INIT configure.ac)" != 1 ]; then
    echo >&2 "Did not find exactly one AC_INIT"
    exit 1
  fi

  sed -i -e '/^AC_INIT(/ s/\(-dev\)\?])/-dev])/' configure.ac

  if [ "$(grep -c 'AC_INIT.*-dev' configure.ac)" != 1 ]; then
    echo >&2 "Unexpect version in configure.ac"
    exit 1
  fi

  popd
}



thisdir=$(dirname "$0")
thisdir=$(readlink -f "$thisdir")
PATH="$thisdir/misc:$PATH"

pkg=tor
pkggitdir="${pkg}"
debgitdir="debian-${pkg}"

(cd "$pkggitdir" && git clean -dxf && git reset --hard HEAD)
(cd "$debgitdir" && git clean -dxf && git reset --hard HEAD)
rm -rf RESULT
rm -f *.tar.gz || true


branch="${branch:-master}"
case "$branch" in
  "master")
    pkgrev=$(cd "$pkggitdir" && git checkout "$branch" && git rev-parse --short=16 HEAD)
    distribution="$pkg-nightly-master"
    ;;
  "0.2.4")
    merge_release_maint "$pkggitdir" release-0.2.4 maint-0.2.4
    distribution="$pkg-nightly-0.2.4.x"
    ;;
  *)
    echo >&2 "Unknown/unsupported branch: '$branch'"
    exit 1
    ;;
esac

fudge_upstream_version "$pkggitdir"

debianrev=$(cd "$debgitdir" && git rev-parse --short HEAD)
ts="$(TZ=UTC date +%Y%m%dT%H%M%SZ)"

# build release tarball
#######################
cd "$pkggitdir"
./autogen.sh
mkdir build-tree
cd build-tree
../configure --disable-silent-rules --enable-gcc-warnings
if [ $(ls -1 *.tar.gz | wc -l) != 0 ] ; then
    echo >&2 "We already have one .tar.gz file before make dist. Confused."
    exit 1
fi
make dist
if [ $(ls -1 *.tar.gz | wc -l) != 1 ] ; then
    echo >&2 "Do not have exactly one .tar.gz file after make dist. Confused."
    exit 1
fi

tgz="$(echo -n *.tar.gz)"
mv -v "$tgz" ../..
cd ../..


# prepare debian source package
###############################
tardir="$(tar taf $tgz 2>/dev/null | head -n1)"
tardir="${tardir%%/}"
dir_version="${tardir##${pkg}-}"
build_version="${dir_version}-$ts"
ddir="$pkg-$build_version"

tar xaf "$tgz"
rm -f "$tgz"

[ "$tardir" = "$ddir" ] || mv "$tardir" "$ddir"
echo "\"$pkgrev\"" > "$ddir/micro-revision.i"

origtar="${pkg}_${build_version}.orig.tar.gz"
tar caf "$origtar" "$ddir"

cp -ra "$debgitdir"/debian "$ddir"
echo "\"$pkgrev+$debianrev\"" > "$ddir/debian/micro-revision.i"

( cd "$ddir" &&
  dch --force-distribution \
    --distribution "$distribution" \
    --force-bad-version \
    --newversion "$build_version-1" \
    "Automated build of "$pkg"-nightly at $ts, git revision $pkgrev with debiantree $debianrev."
)

dpkg-source -b $ddir $origtar

# build them ALL
################
. "$(which build-tor-sources)"
set -x
set +e
backport_all "$pkg" "$ddir" "$origtar" "$build_version-1"
for i in *.dsc; do
    dpkg-source -x "$i"
    (cd "$ddir" && dpkg-genchanges -S) > ${i%.dsc}_src.changes
    rm -r "$ddir"
done

mkdir RESULT
for i in *changes; do dcmd mv -v $i RESULT; done
echo "$build_version" > RESULT/version
