#!/bin/bash

set -e
set -x
set -u

thisscriptdir=$(dirname "$0")
thisscriptdir=$(readlink -f "$thisscriptdir")
"$thisscriptdir"/make-recent-posts > blog-snippets.wmi

mkdir RESULT
mv blog-snippets.wmi RESULT
