#!/bin/bash

set -e
set -x

case "$ARCHITECTURE" in
  i386)
    dd-schroot-cmd -c "$SESSION_ID" -y -- apt-get install gcc-mingw-w64-i686
    ;;
  amd64)
    dd-schroot-cmd -c "$SESSION_ID" -y -- apt-get install gcc-mingw-w64-x86-64
    ;;
  *)
    echo >&2 "Unexpected architecture $ARCHITECTURE."
    exit 1
    ;;
esac
