#!/bin/bash

set -e

dir=$(dirname "$0")
bd="$dir/../etc/build-depends"

if ! [ -e "$bd" ]; then
	echo >&2 "$bd does not exist."
	exit 1
fi

apt-get install -y eatmydata || true
if command -v eatmydata > /dev/null; then prefix=eatmydata; else prefix=""; fi
$prefix apt-get install -y -- $(cat "$bd")
