#!/bin/bash

set -e
set -x
set -u

# Stuff that is run in the chroot as root
setup() {
	echo "Update package list"
	for i in 1 2 3 4 5; do
		apt-get update && break;
		sleep 30;
	done;
	#mkdir -m 0755 -p /usr/share/aclocal

	echo "Install build dependencies"
	apt-get install -y autoconf automake libssl-dev zlib1g-dev libevent-dev asciidoc docbook-xml docbook-xsl xmlto
}

# Stuff that is run in the chroot as user
run() {
	echo "Run autogen"
	./autogen.sh

	echo "Run configure"
	./configure --enable-gcc-warnings --disable-silent-rules

	echo "Run make"
	make -k

	echo "Run test suite"
	make -k check
}



fullpath=$(readlink -f "$0")
dir=$(dirname "$fullpath")
common="$dir/../build-wrapper.common"
for common in "$dir/../build-wrapper.common" "$dir/build-wrapper.common"; do
	if [ -e "$common" ]; then
		. "$common"
		exit 0
	fi
done
echo >&2 "build-wrapper.common not found."
exit 1
