#!/bin/sh
set -x
set -e

dn=$(dirname "$0")
branch0=${dn#*/tor-ci-linux-}
if [ "$branch0" = "$dn" ]; then
  echo >&2 "Did not find branch from dirname $dn"
  exit 1
fi
branch=${branch0%-extra-arm}
if [ "$branch" = "$branch0" ]; then
  echo >&2 "Did not find branch from branch0 $branch0"
  exit 1
fi

fatal_warnings=1
case "$branch" in
  0.2.8)
    case "$SUITE" in
      sid|buster)
        fatal_warnings=0
        ;;
    esac
    ;;
esac
default_flags=""
default_flags="--disable-silent-rules"
if [ "$fatal_warnings" -gt 0 ]; then default_flags="$default_flags --enable-gcc-warnings"; fi

configure_flags=${configure_flags:-"$default_flags"}

(cd tor && ./autogen.sh)
rm -rf build-tree-tor
mkdir build-tree-tor
cd build-tree-tor
../tor/configure $configure_flags
make -k
VERBOSE=yes make -k check
