#!/bin/bash
set -x
set -e

configure_args=""
#configure_args="$configure_args --enable-verbose-debug=${CONFIGURE_VERBOSE_DEBUG%-*}"
#configure_args="$configure_args --enable-thread-support=${CONFIGURE_THREAD_SUPPORT%-*}"
#configure_args="$configure_args --enable-malloc-replacement=${CONFIGURE_MALLOC_REPLACEMENT%-*}"
#configure_args="$configure_args --enable-openssl=${CONFIGURE_OPENSSL%-*}"
#configure_args="$configure_args --enable-debug-mode=${CONFIGURE_DEBUG_MODE%-*}"
configure_args="--host=$CONFIGURE_HOST"

./autogen.sh
./configure --enable-static --disable-shared $configure_args
make -k
