#!/bin/bash

set -e
set -x
set -u

# Stuff that is run in the chroot as root
setup() {
	echo "Update package list"
	for i in 1 2 3 4 5; do
		apt-get update && break;
		sleep 30;
	done;

	echo "Install build dependencies"
	if [ "${SUITE}" = "natty" ]; then
		apt-get install -y python
	else
		apt-get install -y python pyflakes
	fi
}

# Stuff that is run in the chroot as user
run() {
	echo "Cleanup build dir"
	rm -rf build

	echo "Run setup.py"
	python setup.py build

	echo "Run unittests"
	python ./run_tests.py --unit
}



fullpath=$(readlink -f "$0")
dir=$(dirname "$fullpath")
common="$dir/../build-wrapper.common"
for common in "$dir/../build-wrapper.common" "$dir/build-wrapper.common"; do
	if [ -e "$common" ]; then
		. "$common"
		exit 0
	fi
done
echo >&2 "build-wrapper.common not found."
exit 1
