#!/bin/bash
set -x
set -e

configure_flags=${configure_flags:-"--enable-gcc-warnings --disable-silent-rules"}

./autogen.sh

set dummy ${configure_flags}
shift

echo "======================================================="
echo "== Running with configure $*"
echo "======================================================="
rm -rf build-tree-tor
mkdir build-tree-tor
cd build-tree-tor
../configure "$@"
make -k
VERBOSE=yes make -k check
