#!/bin/sh

set -e
set -u
set -x

dn=$(dirname "$0")
branch0=${dn#*/tor-ci-linux-}
branch=${branch0%-rust}
if [ "$branch0" = "$dn" ] ||
   [ "$branch" = "$branch0" ]; then
  echo >&2 "Did not find branch from dirname $dn -> $branch0 -> $branch)"
  exit 1
fi

echo "Think we are in branch $branch."

TOR_RUST_DEPENDENCIES="$(pwd)/ext-tor-rust-dependencies/crates" \
  branch="$branch" \
  configure_flags="--enable-gcc-warnings --disable-silent-rules --enable-rust" \
  "$(dirname "$0")"/../tor-ci-linux/build
