#!/bin/sh

set -e
set -x

./autogen.sh # if we do not run a fresh autogen, libevent-2.0.21-stable will not build
./configure --enable-static --disable-shared
make
make check
make DESTDIR="`pwd`/RESULT-libevent" install
tar czf RESULT-libevent.tar.gz RESULT-libevent
