#!/bin/bash

set -u
set -e

check_arg() {
	name="$1"; shift
	arg="$1"; shift

	if [ -z "${arg:-}" ]; then
		echo >&2 "No $name given."
		exit 1
	fi
	if [[ "$arg" =~ [^A-Za-z0-9-] ]]; then
		echo >&2 "Invalid $name: $arg."
		exit 1
	fi
}

jobname=${JOB_NAME%%/*}
check_arg "job's name" "${jobname:-}"

fullpath=$(readlink -f "$0")
basedir=$(dirname "$fullpath")
jobdir="$basedir/$jobname"

# And check if we have build scripts
if ! [ -d "$jobdir" ]; then
	echo >&2 "$jobdir does not exist or is not a directory."
	exit 1
fi

"$jobdir/build"
