#!/bin/bash

set -e
set -x
set -u

workspace=$(pwd)

torgit="$workspace/tor"
torrev=$(cd tor && git rev-parse HEAD)
webwmlrev=$(cd webwml && git rev-parse HEAD)

(
cd webwml
cp "$workspace"/incoming/blog-snippets.wmi include/blog-recent.wmi
echo "export TORGIT=$torgit/.git" > Makefile.local
make
mkdir -p project/trace
( date -u
  echo "Built on `hostname`."
  echo "Based on webwml:$webwmlrev, tor:$torrev."
) > project/trace/jenkins.torproject.org
rm -rf .git
)

mkdir RESULT
tar caf RESULT/webwml.tar.gz webwml
