#!/bin/sh
set -x
set -e

case "`dpkg --print-architecture`" in
  i386)
    host=i686-w64-mingw32
    ;;
  amd64)
    host=x86_64-w64-mingw32
    ;;
  *)
    echo >&2 "Unexpected architecture $ARCHITECTURE."
    exit 1
    ;;
esac

BASE="`pwd`"
(
  cd libevent
  ./autogen.sh || true
  ./configure --disable-static --host="$host" --prefix="$BASE/RESULT"
  make install
)

tar czf RESULT.libevent RESULT

