#!/bin/bash

set -e
set -x

BASE="`pwd`"
trap "rm -rf '$BASE/UPSTREAM' '$BASE/tor' '$BASE/build-tree' '$BASE/RESULT'" EXIT

for i in libevent openssl zlib; do
	tar xavf "RESULT.$i.tar.gz" --transform 's#^RESULT/#UPSTREAM/#'
	rm "RESULT.$i.tar.gz"
done

(cd tor && ./autogen.sh)

# for dynamic openssl, we need to add openssl's bin dir to PATH
PATH="`pwd`/UPSTREAM/usr/bin:$PATH"
export PATH

rm -rf build-tree
mkdir build-tree
cd build-tree

../tor/configure \
	--with-libevent-dir=../UPSTREAM/usr \
	--with-openssl-dir=../UPSTREAM/usr \
	--with-zlib-dir=../UPSTREAM/usr \
	--enable-gcc-warnings \
	--disable-silent-rules \
	--disable-asciidoc \
	--prefix=/usr \
	CFLAGS='-g -O2 -Wno-error=redundant-decls'
make -k
make -k check
make DESTDIR="`pwd`/../RESULT" install
cd ..

tar caf RESULT.tor.tar.gz RESULT
