#!/bin/sh
set -x
set -e

case "`dpkg --print-architecture`" in
  i386)
    host=i686-w64-mingw32
    ;;
  amd64)
    host=x86_64-w64-mingw32
    ;;
  *)
    echo >&2 "Unexpected architecture $ARCHITECTURE."
    exit 1
    ;;
esac

BASE="`pwd`"
(
cd zlib
make -f win32/Makefile.gcc \
  PREFIX="$host-" \
  BINARY_PATH=/bin INCLUDE_PATH=/include LIBRARY_PATH=/lib \
  SHARED_MODE=1 \
  LOC="-fstack-protector-all -Wstack-protector --param ssp-buffer-size=4 -fno-strict-overflow -Wno-missing-field-initializers -Wformat -Wformat-security -Wl,--dynamicbase -Wl,--nxcompat -lssp" \
  DESTDIR="$BASE/RESULT" \
  install
)

tar czf RESULT.zlib.tar.gz RESULT

