#!/bin/bash

# trigger a jenkins build after a git commit, if we use that repository
# and branch anywhere.

# Copyright 2013 Peter Palfrader
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


set -e
set -u

info() {
    logger -p daemon.info -t "$MYLOGNAME" "$1"
}

croak() {
    logger -s -p daemon.warn -t "$MYLOGNAME" "$1"
    exit 1
}

MYLOGNAME="$(basename "$0")[$$]"
BASE="/srv/jenkins.torproject.org"
PATH="$BASE/bin:$PATH"
JOBGIT="/srv/git.torproject.org/repositories/project/jenkins/jobs.git"
JENKINSFILE="$HOME/.jenkins-config"
[ -e "$JENKINSFILE" ] && . "$JENKINSFILE"
[ -n "${JENKINS_URL:-}" ] || croak "JENKINS_URL not set.  Do it in $JENKINSFILE."


if [ "$#" != 2 ]; then
    croak "Usage: $0 <gitrefsfile> <repo>"
fi
gitrefs="$1"; shift
repo="$1"; shift

GIT_DIR="$JOBGIT" git show master:jobs.yaml |
    $(dirname "$0")/which-triggered "$gitrefs" "$repo" |
    while read job branch digest; do
        json='{"parameter": [
                  { "name": "commit", "value": "'"$digest"'"},
                            { "name": "branch", "value": "'"$branch"'"} ]}'
        curl -X POST "$JENKINS_URL/job/$job/build" -d delay=30 --data-urlencode json="$json"
        info "Triggering jenkins build for ($job, $branch, $digest)."
    done
