#!/bin/bash

set -e
set -x
set -u

get_metadata() {
  local dsc="$1"; shift

  dsc="$(readlink -f "$dsc")"
  local origtar="$(dcmd --orig $dsc)"
  if ! [ -e "$origtar" ]; then
    echo >&2 "File $origtar not found"
    exit 1
  fi

  local tmpdir="`mktemp -d`"
  pushd . >/dev/null
  cd "$tmpdir"

  dpkg-source -x "$dsc" > /dev/null
  cd */

  local dist=$(dpkg-parsechangelog | grep-dctrl -n -s Distribution '')
  local ver=$(dpkg-parsechangelog | grep-dctrl -n -s Version '')

  popd >/dev/null
  rm -rf "$tmpdir"
  echo "$dist $ver"
}

rm -rf build
rm -rf RESULT

case "$SUITE" in
  sid)
    srcchanges=$(ls -1 incoming/*_src.changes | grep -v '~')
    ;;
  *)
    srcchanges=$(ls -1 incoming/*"$SUITE"+*_src.changes)
    ;;
esac

if [ "$(echo "$srcchanges" | wc -l)" != 1 ] || [ -z "$srcchanges" ] ; then
  echo >&2 "Weird number of changes files found."
  exit 1
fi

case "$ARCHITECTURE" in
  amd64)
    extra="--arch-all"
    ;;
  *)
    extra=""
    ;;
esac

BUILD_SUITE="$SUITE"

dsc=$(dcmd --dsc "$srcchanges")

mkdir build
dcmd ln -v "$dsc" build
cd build
dsc=$(basename "$dsc")
metadata=$(get_metadata "$dsc")
read dscdist debian_version <<< "$metadata"

sbuild --arch="$ARCHITECTURE" --dist="$BUILD_SUITE" --nolog --apt-update $extra "$dsc"

changes=$(ls -1 *.changes)
if [ "$(echo "$changes" | wc -l)" != 1 ] || [ -z "$changes" ] ; then
  echo >&2 "Weird number of changes files found."
  exit 1
fi
changestool "$changes" setdistribution "$dscdist"

cd ..

mkdir RESULT
dcmd ln -v "build/$changes" RESULT
# the amd64 job copies the sources to the result
if [ "$ARCHITECTURE" = "amd64" ]; then
  dcmd ln -v "$srcchanges" RESULT
fi
