#!/bin/bash

set -e
err=0

for testsh in $( find -name test.sh ); do
	pushd .
	dir=$(dirname "$testsh")
	echo "=========================================="
	echo $dir
	echo "=========================================="
	cd $dir

	./test.sh || err=1

	popd
done

if [ "$err" -gt 0 ]; then
	exit 1
else
	exit 0
fi

