#!/bin/sh
set -x
set -e

rm -rf UPSTREAM run wine

arch="`dpkg --print-architecture`"
case "$arch" in
  i386)
    host=i686-w64-mingw32
    wine=wine32
    ;;
  amd64)
    host=x86_64-w64-mingw32
    wine=wine64
    ;;
  *)
    echo >&2 "Unexpected architecture $ARCHITECTURE."
    exit 1
    ;;
esac

for upstream in tor; do
  tb="ARCHITECTURE=$arch,SUITE=$SUITE"/RESULT.$upstream.tar.gz
  if ! [ -e "$tb" ]; then
    echo >&2 "Did not find $tb."
    exit 1
  fi
  tar xavf "$tb" --transform 's#^RESULT/#UPSTREAM/#'
  rm "$tb"
done

mkdir run
cp -l UPSTREAM/bin/* run

export WINEPREFIX="`pwd`/wine"

cd run
"$wine" test.exe
